/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen;


import com.diamondfsd.jooq.learn.codegen.tables.TodolistUser;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in todolist
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * USER TABLE
     */
    public static final TodolistUser TODOLIST_USER = TodolistUser.TODOLIST_USER;
}
