/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen;


import com.diamondfsd.jooq.learn.codegen.tables.TodolistUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todolist extends SchemaImpl {

    private static final long serialVersionUID = 1451108516;

    /**
     * The reference instance of <code>todolist</code>
     */
    public static final Todolist TODOLIST = new Todolist();

    /**
     * USER TABLE
     */
    public final TodolistUser TODOLIST_USER = com.diamondfsd.jooq.learn.codegen.tables.TodolistUser.TODOLIST_USER;

    /**
     * No further instances allowed
     */
    private Todolist() {
        super("todolist", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TodolistUser.TODOLIST_USER);
    }
}
