/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.records;


import com.diamondfsd.jooq.learn.codegen.tables.TodolistUser;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodolistUserRecord extends UpdatableRecordImpl<TodolistUserRecord> implements Record6<Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 567617445;

    /**
     * Setter for <code>todolist.todolist_user.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>todolist.todolist_user.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>todolist.todolist_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>todolist.todolist_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>todolist.todolist_user.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>todolist.todolist_user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>todolist.todolist_user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>todolist.todolist_user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>todolist.todolist_user.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>todolist.todolist_user.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>todolist.todolist_user.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>todolist.todolist_user.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TodolistUser.TODOLIST_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return TodolistUser.TODOLIST_USER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return TodolistUser.TODOLIST_USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return TodolistUser.TODOLIST_USER.PASSWORD;
    }

    @Override
    public Field<Timestamp> field5() {
        return TodolistUser.TODOLIST_USER.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field6() {
        return TodolistUser.TODOLIST_USER.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public Timestamp component5() {
        return getCreateTime();
    }

    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    @Override
    public TodolistUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TodolistUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public TodolistUserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TodolistUserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public TodolistUserRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TodolistUserRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TodolistUserRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodolistUserRecord
     */
    public TodolistUserRecord() {
        super(TodolistUser.TODOLIST_USER);
    }

    /**
     * Create a detached, initialised TodolistUserRecord
     */
    public TodolistUserRecord(Integer id, String username, String email, String password, Timestamp createTime, Timestamp updateTime) {
        super(TodolistUser.TODOLIST_USER);

        set(0, id);
        set(1, username);
        set(2, email);
        set(3, password);
        set(4, createTime);
        set(5, updateTime);
    }
}
